### ISSUE TITLE
Regarding NaN entries removal

### ISSUE THREAD

**Issue by deepakkuk** [Maddosaurus/Master_IPython#2]
In Data Sanititazion.ipynb
![screenshot from 2018-12-27 15-31-31](https://user-images.githubusercontent.com/33250220/50476053-a663c900-09ec-11e9-9414-64dc969566d5.png)
 Above line 31, as u say "If this fails because of NaN-Entries, please remove all empty lines in this CSV by hand and try again."
I successfully execute this line but got NaN-Entries. should i remove NaN ENTRIES OR USE SAME FILE

**Comment by Maddosaurus** [comment]
Please try to remove all empty lines in the source CSV and try again. I know it's an ugly fix, but as there is a rewrite pending, fixing this doesn't have precedence. Sorry.
